services:
  jaybankclient:
    image: jaybankclient
    build:
      context: .
      dockerfile: Jaybank.Client/Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - jaybanksupportapp
    volumes:
      - ./Jaybank.Client:/app
    command: ["npm", "run", "start"]

  jaybanksupportapp:
    image: jaybanksupportapp
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8000"]
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - database

  database:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Joyeseosa
      POSTGRES_DB: JayBankDB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
