services:
  jaybankclient:
    image: jaybankclient
    build:
      context: ./Jaybank.Client
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./Jaybank.Client:/app  # For live reload (optional)
      - /app/node_modules      # Prevents overwriting node_modules with host's
    depends_on:
      - jaybanksupportapp
    networks:
      - jaybank-network

  jaybanksupportapp:
    image: jaybanksupportapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Username=postgres;Password=Joyeseosa;Database=JayBankDB
    networks:
      - jaybank-network

  database:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Joyeseosa
      POSTGRES_DB: JayBankDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "JayBankDB"]
      interval: 10s
      retries: 5
    networks:
      - jaybank-network

volumes:
  pgdata:

networks:
  jaybank-network:
    driver: bridge
