"""Third migration

Revision ID: 7f238a868224
Revises: 5d1a493aee54
Create Date: 2025-04-11 12:16:33.779869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f238a868224'
down_revision: Union[str, None] = '5d1a493aee54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_queues', sa.Column('query_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_queues', 'user_chats', ['query_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_queues', type_='foreignkey')
    op.drop_column('user_queues', 'query_id')
    # ### end Alembic commands ###
