"""Fourth migration

Revision ID: cae920d7e6a1
Revises: 7f238a868224
Create Date: 2025-04-12 21:57:58.726230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae920d7e6a1'
down_revision: Union[str, None] = '7f238a868224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credits_transaction', sa.Column('unique_transaction_reference', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credits_transaction', 'unique_transaction_reference')
    # ### end Alembic commands ###
